//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammingChallenge.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgrammingChallenge.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Analysieren der Länder ähnelt.
        /// </summary>
        public static string errorAnalyseCountries {
            get {
                return ResourceManager.GetString("errorAnalyseCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Analysieren des Wetters ähnelt.
        /// </summary>
        public static string errorAnalyseWeather {
            get {
                return ResourceManager.GetString("errorAnalyseWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fläche muss größer als null sein ähnelt.
        /// </summary>
        public static string errorAreaInvalid {
            get {
                return ResourceManager.GetString("errorAreaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag muss positiv sein ähnelt.
        /// </summary>
        public static string errorDayNegative {
            get {
                return ResourceManager.GetString("errorDayNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültige Daten ähnelt.
        /// </summary>
        public static string errorInvalidData {
            get {
                return ResourceManager.GetString("errorInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name darf nicht leer sein ähnelt.
        /// </summary>
        public static string errorNameEmpty {
            get {
                return ResourceManager.GetString("errorNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bevölkerung muss positiv sein ähnelt.
        /// </summary>
        public static string errorPopulationNegative {
            get {
                return ResourceManager.GetString("errorPopulationNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MinTemp darf nicht größer als MaxTemp sein ähnelt.
        /// </summary>
        public static string errorTemperaturesInvalid {
            get {
                return ResourceManager.GetString("errorTemperaturesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Area (km²) ähnelt.
        /// </summary>
        public static string keyNameArea {
            get {
                return ResourceManager.GetString("keyNameArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string keyNameCountryname {
            get {
                return ResourceManager.GetString("keyNameCountryname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day ähnelt.
        /// </summary>
        public static string keyNameDay {
            get {
                return ResourceManager.GetString("keyNameDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MxT ähnelt.
        /// </summary>
        public static string keyNameMaxTemp {
            get {
                return ResourceManager.GetString("keyNameMaxTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MnT ähnelt.
        /// </summary>
        public static string keyNameMinTemp {
            get {
                return ResourceManager.GetString("keyNameMinTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Population ähnelt.
        /// </summary>
        public static string keyNamePopulation {
            get {
                return ResourceManager.GetString("keyNamePopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Länder analysieren ähnelt.
        /// </summary>
        public static string lblAnalyzeCountries {
            get {
                return ResourceManager.GetString("lblAnalyzeCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wetter analysieren ähnelt.
        /// </summary>
        public static string lblAnalyzeWeather {
            get {
                return ResourceManager.GetString("lblAnalyzeWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag ähnelt.
        /// </summary>
        public static string lblDay {
            get {
                return ResourceManager.GetString("lblDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MxT ähnelt.
        /// </summary>
        public static string lblMaxTemp {
            get {
                return ResourceManager.GetString("lblMaxTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MnT ähnelt.
        /// </summary>
        public static string lblMinTemp {
            get {
                return ResourceManager.GetString("lblMinTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurücksetzen ähnelt.
        /// </summary>
        public static string lblReset {
            get {
                return ResourceManager.GetString("lblReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resources/de/bcxp/challenge/countries.csv ähnelt.
        /// </summary>
        public static string pathCountries {
            get {
                return ResourceManager.GetString("pathCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resources/de/bcxp/challenge/weather.csv ähnelt.
        /// </summary>
        public static string pathWeather {
            get {
                return ResourceManager.GetString("pathWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Menschen/km² ähnelt.
        /// </summary>
        public static string unitPopulationDensity {
            get {
                return ResourceManager.GetString("unitPopulationDensity", resourceCulture);
            }
        }
    }
}
